// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AnimationLink: typeof import('./../components/AnimationLink.vue')['default']
    DarkToggle: typeof import('./../components/DarkToggle.vue')['default']
    IconCustomMoon: typeof import('~icons/custom/moon')['default']
    IconCustomSun: typeof import('~icons/custom/sun')['default']
    InfoLable: typeof import('./../components/InfoLable.vue')['default']
    PageFooter: typeof import('./../components/PageFooter.vue')['default']
    SearchInput: typeof import('./../components/SearchInput.vue')['default']
    TopHeader: typeof import('./../components/TopHeader.vue')['default']
  }
}

export { }
